name: react-native-test-actions
on:
  push:
    branches:
      - master
jobs:
  build-android:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease